#ifndef PGC2CALCU_FWD_H
#define PGC2CALCU_FWD_H

#include "pg/pgfwd.h"

#define MESSBASE_NAMESPACE_START PGZXB_ROOT_NAMESPACE_START namespace messbase {
#define MESSBASE_NAMESPACE_END } PGZXB_ROOT_NAMESPACE_END

MESSBASE_NAMESPACE_START
MESSBASE_NAMESPACE_END
#endif
